version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/spc
      - SECRET_KEY=your-secret-key
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=your-email@gmail.com
      - MAIL_PASSWORD=your-password
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=spc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static
    depends_on:
      - web

volumes:
  postgres_data: 