# Configuración de seguridad

# Rate limiting
rate_limit:
  enabled: true
  default_limit: 100
  period: 3600  # 1 hora
  whitelist:
    - 127.0.0.1
    - 192.168.1.0/24

# CORS
cors:
  allowed_origins:
    - https://spc-suplementos.com
    - http://localhost:3000
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed_headers:
    - Content-Type
    - Authorization
  max_age: 3600

# Seguridad de contraseñas
password:
  min_length: 8
  require_uppercase: true
  require_lowercase: true
  require_numbers: true
  require_special: true
  max_attempts: 5
  lockout_duration: 1800  # 30 minutos

# Sesiones
session:
  lifetime: 3600  # 1 hora
  refresh_each_request: true
  secure: true
  httponly: true
  samesite: 'Lax'

# 2FA
two_factor:
  enabled: true
  issuer: 'SPC Suplementos'
  digits: 6
  interval: 30
  backup_codes: 10

# Headers de seguridad
security_headers:
  strict_transport_security:
    enabled: true
    max_age: 31536000
    include_subdomains: true
    preload: true
  content_security_policy:
    default_src: "'self'"
    script_src: "'self' 'unsafe-inline' 'unsafe-eval'"
    style_src: "'self' 'unsafe-inline'"
    img_src: "'self' data: https:"
    font_src: "'self' https://fonts.gstatic.com" 