openapi: 3.0.0
info:
  title: API SPC Suplementos
  version: 1.0.0
  description: API para el sistema de gestión de SPC Suplementos

servers:
  - url: http://localhost:5000/api
    description: Servidor de desarrollo

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    Producto:
      type: object
      properties:
        id:
          type: integer
        codigo:
          type: string
        nombre:
          type: string
        precio_venta:
          type: number
        stock:
          type: integer
    
    Error:
      type: object
      properties:
        message:
          type: string
        error:
          type: string

paths:
  /productos:
    get:
      summary: Obtiene lista de productos
      security:
        - Bearer: []
      responses:
        '200':
          description: Lista de productos exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Crea un nuevo producto
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '201':
          description: Producto creado exitosamente
        '400':
          description: Datos inválidos
        '401':
          description: No autorizado

  /productos/{id}:
    get:
      summary: Obtiene un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - Bearer: []
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Producto no encontrado 